### ISSUE TITLE
Installation issues on Windows: uvloop unsupported, missing requirements file, and incorrect CLI install commands in README

### ISSUE THREAD

**Issue by Mihir-YDC-18** [atlanhq/application-sdk#603]
While trying to set up the project on Windows, I encountered multiple issues that hinder smooth installation and setup:

uvloop does not support Windows
The installation fails with the error:

`uvloop does not support Windows at the moment`

This prevents successful installation on Windows environments.

Missing or incomplete requirements.txt
The repo currently lacks a proper requirements.txt file listing all dependencies clearly, making it difficult to set up the environment reliably.

Incorrect or unclear commands for CLI tools in README
The provided commands for installing Temporal CLI and DAPR CLI on Windows are either incomplete or syntactically incorrect. For example:

Current Temporal CLI command in README:

`Invoke-WebRequest -Uri https://temporal.download/cli/archive/latest?platform=windows&arch=amd64 -OutFile "$env:USERPROFILE\.temporalio\temporal.zip"`

This command misses quotes around the URL and may cause errors in PowerShell.

Suggested corrected Temporal CLI command:

`Invoke-WebRequest -Uri "https://temporal.download/cli/archive/latest?platform=windows&arch=amd64" -OutFile "$env:USERPROFILE\.temporalio\temporal.zip"`

Current DAPR CLI command in README:

`powershell -Command "$script=iwr -useb https://raw.githubusercontent.com/dapr/cli/master/install/install.ps1; $block=[ScriptBlock]::Create($script); invoke-command -ScriptBlock $block -ArgumentList 1.14.1"`

Suggested corrected DAPR CLI command:

`$script=iwr -useb https://raw.githubusercontent.com/dapr/cli/master/install/install.ps1; $block=[ScriptBlock]::Create($script); invoke-command -ScriptBlock $block -ArgumentList 1.14.1`

Expected behavior:

The project should install cleanly on Windows, handling uvloop gracefully or providing alternatives.

A proper requirements.txt should be included to specify all dependencies.

README instructions should contain correct and tested commands for all supported OSes, especially Windows.

**Comment by inishchith** [comment]
hi @Mihir-YDC-18,

thank you for raising this!

we just released a new version [v0.1.1rc20](https://github.com/atlanhq/application-sdk/releases/tag/v0.1.1rc20) also available on [PyPI](https://pypi.org/project/atlan-application-sdk/). This version addresses:
- A fix for `uvloop` not supported for windows.
- Improvements to [documentation](https://github.com/atlanhq/application-sdk/blob/main/docs/docs/setup/WINDOWS.md) for setting up system dependencies on Windows

hopefully this resolves the issues you faced while setting up system dependencies required to build apps.

addressing your concerns around a missing `requirements.txt` - the project doesn't require one, it uses [`uv`](https://docs.astral.sh/uv/) for dependency management.

if you are trying to build apps using the [atlan-application-sdk](https://pypi.org/project/atlan-application-sdk/) - once you have setup your system with required dependencies mentioned in [this document](https://github.com/atlanhq/application-sdk/blob/main/docs/docs/setup/WINDOWS.md), you should try running some [sample apps](https://github.com/atlanhq/atlan-sample-apps).

i am keeping this ticket open to address any further questions or concerns you might have!

**Comment by Mihir-YDC-18** [comment]
Hi,

Thank you for implementing the changes and for the update!

However, when I try to install dependencies using:

`uv sync --all-groups`

I’m still encountering the following error:

`RuntimeError: uvloop does not support Windows at the moment`

![Image](https://github.com/user-attachments/assets/a2bf50cd-d4a5-40e3-aba1-5e52d36d24f7)

I’m attaching a screenshot of the error for reference.

so I would appreciate your help to resolve this issue.

**Comment by araghuraman-atlan** [comment]
You would also need to pull the dependency changes that we made in atlan-sample-apps for the new release. Please clone it again and try the sync from within the new local directory.
